name: React.js CI & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      # Step 3: Install dependencies
      - run: npm i

      # Step 4: Build React project
      - run: npm run build

      # Step 5: Add build folder to the repository (optional)
      - name: Commit build folder
        run: |
          git config --global user.name "github-actions" 
          git config --global user.email "github-actions@github.com"
          git add -f build
          git commit -m "Add build folder" || echo "No changes to commit"
          git push

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
